FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Esse arquivo tem que existir para o nginx funcionar e chamar o nginx.conf, senão retorna 404
RUN mkdir /var/www/html -p && touch /var/www/html/index.php
